import Head from "next/head";
import Projects from "../../Components/Projects";
import Layout from "../../Components/UI/Layout";
import { useRouter } from "next/router";
export default function Home() {
  const router = useRouter();
  const { id } = router.query;
  return (
    <>
      <Head>
        <title> Team Vibhav</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico?" />
      </Head>
      <main>
        <Layout>
          <Projects id={id} />
        </Layout>
      </main>
    </>
  );
}
